
/*
 * Main.eq
 * Generated by Eqela Studio 2.0b7.4
 */

public class Main: LayerWidget
{

	public void initialize() {
		base.initialize();
		set_size_request_override(px("50mm"), px("70mm"));
		add(CanvasWidget.for_colors(Color.instance("blue"),Color.instance("green")));
		add(LabelWidget.for_string("Daryl Farts").set_font(Theme.font().modify("8mm bold color=#ff69b4 outline-color=#d3d3d3")));
			
	}
	
}
